development:
  exception_recipients: [me@example.com]
  exception_email_prefix: '[Waystation] '
  exception_sender_address: '"Error Notifier" <notifier@example.com>'
  host: 'ridepilot.local'

test:
  exception_recipients: [me@example.com]
  exception_email_prefix: '[Waystation] '
  exception_sender_address: '"Error Notifier" <notifier@example.com>'
  host: 'ridepilot.test'

production:
  exception_recipients: [me@example.com]
  exception_email_prefix: '[Waystation] '
  exception_sender_address: '"Error Notifier" <notifier@example.com>'
  host: 'rideconn.dev.openplans.org/ridepilot'
