# all configurable environments: 
#   development
#   test
#   integration
#   qa
#   production

development:
  RIDE_CONNECTION_ADMIN_EMAIL:
  RIDE_CONNECTION_ADMIN_PASSWORD:
  RIDEPILOT_HOST:
  SYSTEM_SEND_FROM_ADDRESS:
  SMTP_MAIL_ADDR:
  SMTP_MAIL_PORT:
  SMTP_MAIL_DOMAIN:
  SMTP_MAIL_USER_NAME:
  SMTP_MAIL_PASSWORD:

test:
  RIDE_CONNECTION_ADMIN_EMAIL:
  RIDE_CONNECTION_ADMIN_PASSWORD:
  RIDEPILOT_HOST:
  SYSTEM_SEND_FROM_ADDRESS:
  SMTP_MAIL_ADDR:
  SMTP_MAIL_PORT:
  SMTP_MAIL_DOMAIN:
  SMTP_MAIL_USER_NAME:
  SMTP_MAIL_PASSWORD:               