RIDE_CONNECTION_ADMIN_EMAIL:
RIDE_CONNECTION_ADMIN_PASSWORD:
SYSTEM_SEND_FROM_ADDRESS:
SMTP_MAIL_ADDR:
SMTP_MAIL_PORT:
SMTP_MAIL_DOMAIN:
SMTP_MAIL_USER_NAME:
SMTP_MAIL_PASSWORD:

development:
  RIDEPILOT_HOST:                

test:
  RIDEPILOT_HOST:                 

integration:
  RIDEPILOT_HOST:                 

qa:
  RIDEPILOT_HOST:                 

production:
  RIDEPILOT_HOST:                 